_vehicle = _this;

_vehicle addWeaponTurret ["autocannon_40mm_VTOL_01", [1]];
_vehicle addMagazineTurret ["240Rnd_40mm_GPR_Tracer_Red_shells", [1]];
_vehicle addMagazineTurret ["240Rnd_40mm_GPR_Tracer_Red_shells", [1]];
_vehicle addMagazineTurret ["240Rnd_40mm_GPR_Tracer_Red_shells", [1]];
_vehicle addMagazineTurret ["160Rnd_40mm_APFSDS_Tracer_Red_shells", [1]];
_vehicle addMagazineTurret ["160Rnd_40mm_APFSDS_Tracer_Red_shells", [1]];
_vehicle addMagazineTurret ["160Rnd_40mm_APFSDS_Tracer_Red_shells", [1]];
_vehicle addWeaponTurret ["Gatling_30mm_Plane_CAS_01_F", [1]];
_vehicle addMagazineTurret ["1000Rnd_Gatling_30mm_Plane_CAS_01_F", [1]];
_vehicle addMagazineTurret ["1000Rnd_Gatling_30mm_Plane_CAS_01_F", [1]];
_vehicle addWeaponTurret ["autocannon_40mm_VTOL_01", [2]];
_vehicle addMagazineTurret ["240Rnd_40mm_GPR_Tracer_Red_shells", [2]];
_vehicle addMagazineTurret ["240Rnd_40mm_GPR_Tracer_Red_shells", [2]];
_vehicle addMagazineTurret ["240Rnd_40mm_GPR_Tracer_Red_shells", [2]];
_vehicle addMagazineTurret ["160Rnd_40mm_APFSDS_Tracer_Red_shells", [2]];
_vehicle addMagazineTurret ["160Rnd_40mm_APFSDS_Tracer_Red_shells", [2]];
_vehicle addMagazineTurret ["160Rnd_40mm_APFSDS_Tracer_Red_shells", [2]];
_vehicle addWeaponTurret ["Gatling_30mm_Plane_CAS_01_F", [2]];
_vehicle addMagazineTurret ["1000Rnd_Gatling_30mm_Plane_CAS_01_F", [2]];
_vehicle addMagazineTurret ["1000Rnd_Gatling_30mm_Plane_CAS_01_F", [2]];
_vehicle setVariable ["BIS_enableRandomization", false];
_vehicle setObjectTextureGlobal [0, "assassin\pics\Ghosthawk\ghosthawk1.jpg"];
_vehicle setObjectTextureGlobal [1, "assassin\pics\Ghosthawk\ghosthawk2jpg"];
_vehicle addMagazineTurret ["240Rnd_CMFlare_Chaff_Magazine", [-1]];
_vehicle addMagazineTurret ["240Rnd_CMFlare_Chaff_Magazine", [-1]];
_vehicle addMagazineTurret ["240Rnd_CMFlare_Chaff_Magazine", [-1]];
_vehicle addMagazineTurret ["240Rnd_CMFlare_Chaff_Magazine", [-1]];
_vehicle addWeaponTurret ["GBU12BombLauncher", [-1]];
_vehicle addMagazineTurret ["2Rnd_GBU12_LGB", [-1]];
_vehicle addMagazineTurret ["2Rnd_GBU12_LGB", [-1]];
_vehicle addMagazineTurret ["2Rnd_GBU12_LGB", [-1]];
_vehicle addMagazineTurret ["2000Rnd_65x39_Belt_Tracer_Red", [1]];
_vehicle addMagazineTurret ["2000Rnd_65x39_Belt_Tracer_Red", [2]];

