private ["_this"];

_vehicle = _this select 0;

_vehicle addWeaponTurret ["autocannon_40mm_VTOL_01", [1]];
_vehicle addMagazineTurret ["240Rnd_40mm_GPR_Tracer_Red_shells", [1]];
_vehicle addMagazineTurret ["240Rnd_40mm_GPR_Tracer_Red_shells", [1]];
_vehicle addMagazineTurret ["240Rnd_40mm_GPR_Tracer_Red_shells", [1]];
_vehicle addMagazineTurret ["160Rnd_40mm_APFSDS_Tracer_Red_shells", [1]];
_vehicle addMagazineTurret ["160Rnd_40mm_APFSDS_Tracer_Red_shells", [1]];
_vehicle addMagazineTurret ["160Rnd_40mm_APFSDS_Tracer_Red_shells", [1]];
_vehicle addWeaponTurret ["Gatling_30mm_Plane_CAS_01_F", [1]];
_vehicle addMagazineTurret ["1000Rnd_Gatling_30mm_Plane_CAS_01_F", [1]];
_vehicle addMagazineTurret ["1000Rnd_Gatling_30mm_Plane_CAS_01_F", [1]];
_vehicle addWeaponTurret ["autocannon_40mm_VTOL_01", [2]];
_vehicle addMagazineTurret ["240Rnd_40mm_GPR_Tracer_Red_shells", [2]];
_vehicle addMagazineTurret ["240Rnd_40mm_GPR_Tracer_Red_shells", [2]];
_vehicle addMagazineTurret ["240Rnd_40mm_GPR_Tracer_Red_shells", [2]];
_vehicle addMagazineTurret ["160Rnd_40mm_APFSDS_Tracer_Red_shells", [2]];
_vehicle addMagazineTurret ["160Rnd_40mm_APFSDS_Tracer_Red_shells", [2]];
_vehicle addMagazineTurret ["160Rnd_40mm_APFSDS_Tracer_Red_shells", [2]];
_vehicle addWeaponTurret ["Gatling_30mm_Plane_CAS_01_F", [2]];
_vehicle addMagazineTurret ["1000Rnd_Gatling_30mm_Plane_CAS_01_F", [2]];
_vehicle addMagazineTurret ["1000Rnd_Gatling_30mm_Plane_CAS_01_F", [2]];
_vehicle setVariable ["BIS_enableRandomization", false];
_vehicle setObjectTextureGlobal [0,"assassin\pics\trc.jpg"];
_vehicle setObjectTextureGlobal [1, "assassin\pics\trc.jpg"];
_vehicle setObjectTextureGlobal [2, "assassin\pics\trc.jpg"];
_vehicle setObjectTextureGlobal [3, "assassin\pics\trc.jpg"];
_vehicle addMagazineTurret ["168Rnd_CMFlare_Chaff_Magazine", [-1]];
_vehicle addMagazineTurret ["168Rnd_CMFlare_Chaff_Magazine", [-1]];
_vehicle addMagazineTurret ["168Rnd_CMFlare_Chaff_Magazine", [-1]];
_vehicle addWeaponTurret ["GBU12BombLauncher", [-1]];
_vehicle addMagazineTurret ["2Rnd_GBU12_LGB", [-1]];
_vehicle addMagazineTurret ["2Rnd_GBU12_LGB", [-1]];
_vehicle addMagazineTurret ["2Rnd_GBU12_LGB", [-1]];
_vehicle removeWeaponTurret ["LMG_Minigun_Transport", [1]];
_vehicle removeWeaponTurret ["LMG_Minigun_Transport", [2]];
_vehicle removeMagazineTurret ["2000Rnd_65x39_Belt_Tracer_Red", [1]];
_vehicle removeMagazineTurret ["2000Rnd_65x39_Belt_Tracer_Red", [2]];